<a href="https://colab.research.google.com/github/nV1a/ZezeroKD_VVS_2026/blob/main/titanic(vvs).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('titanic.csv')
n = int(input("Введите колво строк: "))
display(df.head(n))
display(df.tail(5))
print(f"Строк: {df.shape[0]}, Столбцов: {df.shape[1]}")
print("Столбцы:", df.columns.tolist())
print("Типы данных:", df.dtypes)
num_f = ['Age', 'Fare', 'SibSp', 'Parch']
cat_f = ['Pclass', 'Sex', 'Embarked', 'Survived', 'Cabin', 'Name', 'Ticket']
display(df[num_f].describe())
print('Пассажиры по классам:', df['Pclass'].value_counts())
print('Уникальных портов посадки:', df['Embarked'].nunique())
print('Пропуски по столбцам:', df.isnull().sum())
print('Процент пропусков:', df.isnull().mean() * 100)
max_missing_col = df.isnull().sum().idxmax()
print(f'Больше всего пропусков в столбце: {max_missing_col}')
age_before = {
    'Среднее': df['Age'].mean(),
    'Медиана': df['Age'].median(),
    'Минимум': df['Age'].min(),
    'Максимум': df['Age'].max(),
    'Ст. отклонение': df['Age'].std(),
    'Колво': df['Age'].count()
}

age_median = df['Age'].median()
df['Age'] = df['Age'].fillna(age_median)
age_after = {
    'Среднее': df['Age'].mean(),
    'Медиана': df['Age'].median(),
    'Минимум': df['Age'].min(),
    'Максимум': df['Age'].max(),
    'Ст. отклонение': df['Age'].std(),
    'Колво': df['Age'].count()
}

comparison_df = pd.DataFrame([age_before, age_after], index=['До обработки', 'После обработки'])
display(comparison_df)
shape_before = df.shape
df = df.dropna(subset=['Embarked'])
if df['Cabin'].isnull().mean() > 0.5:
  df = df.drop(columns=['Cabin'])
print('Остаток пропусков:', df.isnull().sum())
print(f'Размер до: {shape_before}, после: {df.shape}')
survived_arr = df['Survived'].to_numpy()
sex_arr = df['Sex'].to_numpy()
age_arr = df['Age'].to_numpy()
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
fare_arr = df['Fare'].to_numpy()
survival_rate = np.mean(survived_arr) * 100
print(f'Общий процент выживших: {survival_rate:.2f}%')
male_survived = np.mean(survived_arr[sex_arr == 'male']) * 100
female_survived = np.mean(survived_arr[sex_arr == 'female']) * 100
male_age = np.mean(age_arr[sex_arr == 'male'])
female_age = np.mean(age_arr[sex_arr == 'female'])
male_surv_age = np.mean(age_arr[(sex_arr == 'male') & (survived_arr == 1)])
male_dead_age = np.mean(age_arr[(sex_arr == 'male') & (survived_arr == 0)])
female_surv_age = np.mean(age_arr[(sex_arr == 'female') & (survived_arr == 1)])
female_dead_age = np.mean(age_arr[(sex_arr == 'female') & (survived_arr == 0)])
print(f'Билет - мин: {np.min(fare_arr):.2f}, макс: {np.max(fare_arr):.2f}, среднее: {np.mean(fare_arr):.2f}')
print(f'Ст. отклонение возраста: {np.std(age_arr):.2f}')
numpy_stats = pd.DataFrame({
    'Процент выживших': [male_survived, female_survived],
    'Средний возраст': [male_age, female_age],
    'Ср. возраст выживших': [male_surv_age, female_surv_age],
    'Ср. возраст погибших': [male_dead_age, female_dead_age]
}, index=['Мужчины', 'Женщины'])
display(numpy_stats)

task1 = df[(df['Sex'] == 'male') & (df['Age'] > 30) & (df['Pclass'] == 1)]
print('Task1', len(task1))
display(task1.head(10))

task2 = df[((df['Age'] < 18) | (df['Sex'] == 'female')) & (df['Survived'] == 1)]
print('Task2', len(task2))

mean_fare_3 = df[df['Pclass'] == 3]['Fare'].mean()
task3 = df[(df['Pclass'] == 3) & (df['Fare'] > mean_fare_3)]
print('Task3', len(task3))

task4 = df[(df['Age'] >= 20) & (df['Age'] <= 40) & (df['Embarked'] == 'S')]
print('Task4', len(task4))


group_class_sex = df.groupby(['Pclass', 'Sex']).agg(
    Количество=('PassengerId', 'count'),
    Средний_возраст=('Age', 'mean'),
    Доля_выживших_процент=('Survived', lambda x: x.mean() * 100),
    Средняя_цена_билета=('Fare', 'mean')
).reset_index()
display(group_class_sex)

group_embarked = df.groupby('Embarked').agg(
    Количество=('PassengerId', 'count'),
    Доля_выживших_процент=('Survived', lambda x: x.mean() * 100)
).reset_index()
display(group_embarked)

best_class = df.groupby('Pclass')['Survived'].mean().idxmax()
print(f'Класс с наиб долей выживших: {best_class}')

df.to_csv('titanic_processed.csv', index=False)
group_class_sex.to_csv('titanic_statistics.csv', index=False)
df_test = pd.read_csv('titanic_processed.csv')
print('Успех', len(df_test))

Введите колво строк: 800

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Строк: 418, Столбцов: 12
Столбцы: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
Типы данных: PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

              Age        Fare       SibSp       Parch
count  332.000000  417.000000  418.000000  418.000000
mean    30.272590   35.627188    0.447368    0.392344
std     14.181209   55.907576    0.896760    0.981429
min      0.170000    0.000000    0.000000    0.000000
25%     21.000000    7.895800    0.000000    0.000000
50%     27.000000   14.454200    0.000000    0.000000
75%     39.000000   31.500000    1.000000    0.000000
max     76.000000  512.329200    8.000000    9.000000

Пассажиры по классам: Pclass
3    218
1    107
2     93
Name: count, dtype: int64
Уникальных портов посадки: 3
Пропуски по столбцам: PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64
Процент пропусков: PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64
Больше всего пропусков в столбце: Cabin

                   Среднее  Медиана  Минимум  Максимум  Ст. отклонение  Колво
До обработки     30.272590     27.0     0.17      76.0       14.181209    332
После обработки  29.599282     27.0     0.17      76.0       12.703770    418

Остаток пропусков: PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64
Размер до: (418, 12), после: (418, 11)
Общий процент выживших: 36.36%
Билет - мин: 0.00, maкс: 512.33, среднее: 35.58
Ст. отклонение возраста: 12.69

/usr/local/lib/python3.13/dist-packages/numpy/_core/fromnumeric.py:3904: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.13/dist-packages/numpy/_core/_methods.py:147: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

,Процент выживших,Средний возраст,Ср. возраст выживших,Ср. возраст погибших
Мужчины,0.0,29.522218,NaN,29.522218
Женщины,100.0,29.734145,29.734145,NaN

Task1 36

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,S
20,912,0,1,"Rothschild, Mr. Martin",male,55.0,1,0,PC 17603,59.4000,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,S
46,938,0,1,"Chevre, Mr. Paul Romaine",male,45.0,0,0,PC 17594,29.7000,C
67,959,0,1,"Moore, Mr. Clarence Bloomfield",male,47.0,0,0,113796,42.4000,S
68,960,0,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.0,0,0,2543,28.5375,C
75,967,0,1,"Keeping, Mr. Edwin",male,32.5,0,0,113503,211.5000,C
81,973,0,1,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,S
82,974,0,1,"Case, Mr. Howard Brown",male,49.0,0,0,19924,26.0000,S
118,1010,0,1,"Beattie, Mr. Thomson",male,36.0,0,0,13050,75.2417,C

Task2 152
Task3 63
Task4 179

,Pclass,Sex,Количество,Средний_возраст,Доля_выживших_процент,Средняя_цена_билета
0,1,female,50,40.760000,100.0,115.591168
1,1,male,57,38.859649,0.0,75.586551
2,2,female,30,24.464000,100.0,26.438750
3,2,male,63,30.690476,0.0,20.184654
4,3,female,72,24.273194,100.0,13.735129
5,3,male,146,25.372671,0.0,11.844349

  Embarked  Количество  Доля_выживших_процент
0        C         102              39.215686
1        Q          46              52.173913
2        S         270              32.592593

Класс с наиб долей выживших: 1
Успех 418

Пропуски: Максимальное количество в столбцах Cabin (327 шт. / 78.2%) и Age (86 шт. / 20.5%)

Влияние обработки: Столбец Cabin удален из-за обилия пропусков. Заполнение пропусков возраста медианой (27.0) снизило средний возраст с 30.27 до 29.60 и уменьшило стандартное отклонение с 14.18 до 12.70 (данные стали кучнее)

Выживаемость по полу: В данном датасете выжило 100% женщин и 0% мужчин.

Выживаемость по классу: Максимальная доля выживших зафиксирована в 1 классе.

Полезные инструменты: В Pandas - fillna() для безопасного заполнения пропусков, логические маски (&, |) для фильтрации и groupby() для агрегации; в NumPy - np.mean() и np.std() для быстрых расчетов.